version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule: { interval: monthly }
    groups:
      all-actions-version-updates:
        applies-to: version-updates
        patterns: [ '*' ]
      all-actions-security-updates:
        applies-to: security-updates
        patterns: [ '*' ]
    cooldown:
      default-days: 7
      # no semver support for github-actions
      # => no specific configuration for this
      include:
        - "*"

  # Update Rust dependencies
  - package-ecosystem: cargo
    directory: '/'
    schedule: { interval: monthly }
    open-pull-requests-limit: 10
    groups:
      all-cargo-version-updates:
        applies-to: version-updates
        patterns: [ '*' ]
      all-cargo-security-updates:
        applies-to: security-updates
        patterns: [ '*' ]
    cooldown:
      default-days: 7
      include:
        - "*"

  # Update Martin UI NPM dependencies
  - package-ecosystem: npm
    directory: '/martin/martin-ui/'
    schedule: { interval: monthly }
    open-pull-requests-limit: 10
    groups:
      all-npm-ui-version-updates:
        applies-to: version-updates
        patterns: [ '*' ]
        exclude-patterns:
          - '@biomejs/biome'
          - 'tailwindcss'
      all-npm-ui-security-updates:
        applies-to: security-updates
        patterns: [ '*' ]
    cooldown:
      default-days: 7
      include:
        - "*"

  # Update Demo frontend NPM dependencies
  - package-ecosystem: npm
    directory: '/demo/frontend/'
    schedule: { interval: monthly }
    open-pull-requests-limit: 10
    groups:
      all-npm-fe-version-updates:
        applies-to: version-updates
        patterns: [ '*' ]
        exclude-patterns:
          - '@biomejs/biome'
      all-npm-fe-security-updates:
        applies-to: security-updates
        patterns: [ '*' ]
    cooldown:
      default-days: 7
      include:
        - "*"
