version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule: { interval: monthly }
    groups:
      all-actions-version-updates:
        applies-to: version-updates
        patterns: [ '*' ]
      all-actions-security-updates:
        applies-to: security-updates
        patterns: [ '*' ]
    cooldown:
      default-days: 7
      include:
        - "*"

  - package-ecosystem: cargo
    directory: '/'
    schedule: { interval: monthly }
    open-pull-requests-limit: 10
    groups:
      all-cargo-version-updates:
        applies-to: version-updates
        patterns: [ '*' ]
      all-cargo-security-updates:
        applies-to: security-updates
        patterns: [ '*' ]
    cooldown:
      default-days: 7
      include:
        - "*"

  - package-ecosystem: npm
    directories:
      - '/martin/martin-ui/'
      - '/demo/frontend/'
    schedule: { interval: monthly }
    open-pull-requests-limit: 10
    groups:
      all-npm-version-updates:
        applies-to: version-updates
        patterns: [ '*' ]
        exclude-patterns:
          - '@biomejs/biome'
      all-npm-security-updates:
        applies-to: security-updates
        patterns: [ '*' ]
    cooldown:
      default-days: 7
      include:
        - "*"

  - package-ecosystem: docker
    directories:
      - '/demo/db'
      - '/demo/frontend'
    schedule: { interval: monthly }
    open-pull-requests-limit: 10
    groups:
      all-npm-version-updates:
        applies-to: version-updates
        patterns: [ '*' ]
      all-npm-security-updates:
        applies-to: security-updates
        patterns: [ '*' ]
    cooldown:
      default-days: 7
      include:
        - "*"
      exclude:
        - "ghcr.io/maplibre/martin"
