[workspace]
dependencies_update = true
git_release_type = "auto"
changelog_update = true

[[package]]
name = "martin-core"

[[package]]
name = "martin-tile-utils"
changelog_update = false
git_release_enable = false

[[package]]
name = "martin"
changelog_include = ["martin", "martin-core", "martin-tile-utils", "mbtiles"]

[[package]]
name = "mbtiles"
changelog_include = ["martin-tile-utils", "mbtiles"]

[changelog]
protect_breaking_commits = true
