[book]
authors = ["MapLibre contributors"]
language = "en"
multilingual = false
src = "src"
title = "Martin Tile Server Documentation"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/maplibre/martin"
edit-url-template = "https://github.com/maplibre/martin/edit/main/docs/{path}"
