[book]
authors = ["MapLibre contributors"]
language = "en"
src = "src"
title = "Martin Tile Server Documentation"

[build]
build-dir = "../target/book"

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/maplibre/martin"
edit-url-template = "https://github.com/maplibre/martin/edit/main/docs/{path}"
additional-css = ["theme/tabs.css"]
additional-js = ["theme/tabs.js"]

[preprocessor.tabs]
